name: Generate Dates
on:
  schedule:  # execute every 12 hours
    - cron:  "* */12 * * *"
  workflow_dispatch:
jobs:
  build:
    name: jobs to update dates
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ambika97-p
          svg_out_path: dist/github-contriburion-grid-snake.svg
      - uses: crazy-max/graction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
           GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN  }}
    
